name = "sveltekit-cloudflare-blog"
compatibility_date = "2026-04-27"
main = ".svelte-kit/cloudflare/_worker.js"

[assets]
directory = ".svelte-kit/cloudflare"
binding = "ASSETS"

[observability]
enabled = true

[[d1_databases]]
binding = "COMMENTS_DB"
database_name = "blog-comments"
database_id = "2dbabfab-d9e0-48d4-a971-d0dabe667ced"
